export const GET_MESSAGE = "GET MESSAGE";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAIL = "GET_MESSAGE_FAIL";

export const ADD_MESSAGE = "ADD MESSAGE";
export const DELETE_MESSAGE = "DELETE MESSAGE";
export const DELETE_MESSAGE_FAIL = "DELETE MESSAGE_FAIL";